platform :ios, '7.0'
xcodeproj 'SevenSitters.xcodeproj'

# pod 'NSLogger'
pod 'CrittercismSDK'
pod 'Facebook-iOS-SDK'
pod 'FMDB'
pod 'GRMustache'
pod 'ISO8601DateFormatter'
pod 'CardIO'
pod 'Mixpanel'
pod 'NSDate-Extensions'
pod 'ReactiveCocoa'
pod 'Stripe'
pod 'SVProgressHUD'
pod 'TestFlightSDK'
