// Generated by IB v0.4.3 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation AppDelegate
@end

@implementation BookingController
@end

@implementation ChatController
@end

@implementation ExpiredController
@end

@implementation HelloController
@end

@implementation RecommendedSittersController
@end

@implementation SearchSittersController
@end

@implementation SettingsController
@end

@implementation SitterCircleController
@end

@implementation SitterDetailsController
@end

@implementation SittersController
@end

@implementation SplashController
@end

@implementation TimeSelectionController
@end

@implementation TimeSelection
@end

@implementation UpdatesController
@end

@implementation WelcomeController
@end

@implementation NSDate
@end

@implementation ExpirationChecker
@end

@implementation NSAttributedString
@end

@implementation Account
@end

@implementation Family
@end

@implementation Sitter
@end

@implementation Update
@end

@implementation RACSignal
@end

@implementation Fixnum
@end

@implementation RACMotionKeyPathAgent
@end

@implementation Object
@end

@implementation Server
@end

@implementation EmulatedServer
@end

@implementation Storage
@end

@implementation UIFont
@end

@implementation UIView
@end

@implementation Scheduler
@end

@implementation Debounced
@end

@implementation HexagonLayout
@end

