// Generated by IB v0.4.3 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <AVFoundation/AVFoundation.h>
#import <Accelerate/Accelerate.h>
#import <AdSupport/AdSupport.h>
#import <AudioToolbox/AudioToolbox.h>
#import <CFNetwork/CFNetwork.h>
#import <CoreGraphics/CoreGraphics.h>
#import <CoreLocation/CoreLocation.h>
#import <CoreMedia/CoreMedia.h>
#import <CoreTelephony/CoreTelephony.h>
#import <CoreVideo/CoreVideo.h>
#import <Foundation/Foundation.h>
#import <MapKit/MapKit.h>
#import <MobileCoreServices/MobileCoreServices.h>
#import <OpenGLES/OpenGLES.h>
#import <QuartzCore/QuartzCore.h>
#import <Security/Security.h>
#import <SystemConfiguration/SystemConfiguration.h>
#import <UIKit/UIKit.h>
#import <SystemConfiguration/SystemConfiguration.h>

@interface AppDelegate: UIResponder <UIApplicationDelegate>
-(IBAction) buildDate;
-(IBAction) buildNumber;
-(IBAction) firebaseRoot;
-(IBAction) firebaseEnvironment;
-(IBAction) serviceEnvironmentName;
-(IBAction) registerForRemoteNotifications;
-(IBAction) installExpirationObserver;
-(IBAction) tabControllers;
-(IBAction) attachSplashViewTo:(id) view;
-(IBAction) presentSplashView;
-(IBAction) presentConnectionProgressHUD;
-(IBAction) getAPIToken:(id) tokenName;
-(IBAction) initializeCrittercism;
-(IBAction) initializeMixpanel;
-(IBAction) initializeStripe;
-(IBAction) initializeTestFlight;

@end

@interface BookingController: UIViewController
-(IBAction) viewDidLoad;
-(IBAction) timeSelectionDidChangeTo:(id) timeSelection;
-(IBAction) inviteSitter;
-(IBAction) peoplePickerNavigationControllerDidCancel:(id) controller;
-(IBAction) presentSuggestedSitters;
-(IBAction) presentDetailsForSitter:(id) sitter;
-(IBAction) timeSelection;
-(IBAction) sitterDetailsController;
-(IBAction) recommendedSittersController;

@end

@interface ChatController: UIViewController
-(IBAction) viewWillAppear:(id) animated;

@end

@interface ExpiredController: UIViewController
@end

@interface HelloController: UIViewController

@property IBOutlet UIScrollView * scroller;
@property IBOutlet id btn_hello;

-(IBAction) say_hello:(id) sender;

@end

@interface RecommendedSittersController: UITableViewController
-(IBAction) viewDidLoad;
-(IBAction) sitters;
-(IBAction) updateSitterCountText;
-(IBAction) numberOfSectionsInTableView:(id) tableView;

@end

@interface SearchSittersController: UITableViewController
-(IBAction) prefersStatusBarHidden;
-(IBAction) data;
-(IBAction) viewDidLoad;
-(IBAction) viewDidAppear:(id) animated;
-(IBAction) viewDidDisappear:(id) animated;

@end

@interface SettingsController: Formotion::FormController
-(IBAction) init;
-(IBAction) viewDidDisappear:(id) view;
-(IBAction) userDidCancelPaymentViewController:(id) scanViewController;
-(IBAction) updateForm;
-(IBAction) createForm;

@end

@interface SitterCircleController: NSObject
-(IBAction) viewDidLoad;
-(IBAction) sitter;
-(IBAction) available;
-(IBAction) layoutSublayersOfLayer:(id) layer;
-(IBAction) updateLayerContents;
-(IBAction) createRingLayerImage;
-(IBAction) createNumberLayerImage;
-(IBAction) sitterImage;

@end

@interface SitterDetailsController: UIViewController
-(IBAction) stylesheet;
-(IBAction) sitter;
-(IBAction) updateButtonText;
-(IBAction) template;
-(IBAction) renderTemplate;
-(IBAction) webViewDidFinishLoad:(id) webview;

@end

@interface SittersController: UIViewController
-(IBAction) stylesheet;
-(IBAction) viewDidLoad;
-(IBAction) family;
-(IBAction) createRecommendedSittersButton;
-(IBAction) createInviteSitterButton;
-(IBAction) createAddSittersText;
-(IBAction) updateSitterAvailability;
-(IBAction) createSitterViews;
-(IBAction) registerObservers;

@end

@interface SitterProfileEditController: UIViewController

@property IBOutlet UILabel * fullName;
@property IBOutlet UILabel * displayName;
@property IBOutlet UIButton * birthDate;
@property IBOutlet UITextView * description;

-(IBAction) signOutButtonTouched:(id) sender;

@end

@interface SplashController: UIViewController
-(IBAction) splashImage;

@end

@interface TimeSelectionController: UIViewController
-(IBAction) viewDidLoad;
-(IBAction) createDaySelectionViews;
-(IBAction) createHourSelectionViews;
-(IBAction) findTouchEffectHandleTarget:(id) touch;

@end

@interface TimeSelection: NSObject
-(IBAction) startTime;
-(IBAction) endTime;
-(IBAction) onDate:(id) date;
-(IBAction) hourToTime:(id) hour;

@end

@interface UpdatesController: UITableViewController
-(IBAction) viewDidLoad;
-(IBAction) viewDidAppear:(id) animated;

@end

@interface WelcomeController: UIViewController

@property IBOutlet UILabel * greeting;

-(IBAction) backFromEditSitterProfile:(UIStoryboardSegue *) segue;
-(IBAction) parentButtonTouched:(id) sender;
-(IBAction) sitterButtonTouched:(id) sender;

@end

@interface NSDate: NSObject
-(IBAction) ISO8601StringFromDate;
-(IBAction) relativeDayFromDate;

@end

@interface ExpirationChecker: NSObject
-(IBAction) initialize;
-(IBAction) buildDate;
-(IBAction) expirationDate;
-(IBAction) dateFromProperty:(id) propertyName;

@end

@interface NSAttributedString: NSObject
@end

@interface Account: NSObject
-(IBAction) initialize;
-(IBAction) initializeLoginStatus;
-(IBAction) user;
-(IBAction) login;
-(IBAction) logout;
-(IBAction) accountKey;
-(IBAction) deviceToken;
-(IBAction) injectUserInstanceMethods:(id) user;
-(IBAction) displayName;
-(IBAction) email;
-(IBAction) locationName;
-(IBAction) auth;
-(IBAction) firebaseRoot;
-(IBAction) firebaseEnvironment;
-(IBAction) family;
-(IBAction) updateUserDataSubscription;

@end

@interface Family: NSObject
-(IBAction) initialize;
-(IBAction) updateFrom:(id) data;
-(IBAction) sitters;
-(IBAction) recommended_sitters;
-(IBAction) setSitterCount:(id) count;
-(IBAction) canAddSitter:(id) sitter;
-(IBAction) addSitter:(id) sitter;
-(IBAction) resetSitterList;

@end

@interface Sitter: NSObject
-(IBAction) initialize:(id) data;
-(IBAction) updateFrom:(id) data;
-(IBAction) availableAt:(id) timespan;
-(IBAction) imagePath;
-(IBAction) image;
-(IBAction) maskedImage;

@end

@interface Update: NSObject
-(IBAction) initialize:(id) data;
-(IBAction) image;
-(IBAction) person;

@end

@interface RACSignal: NSObject
-(IBAction) boolean;
-(IBAction) first;
-(IBAction) main_thread;
-(IBAction) latest;

@end

@interface Fixnum: NSObject
-(IBAction) key:(id) key;
-(IBAction) keyPath;
-(IBAction) rac:(id) object;

@end

@interface RACMotionKeyPathAgent: NSObject
-(IBAction) key:(id) key;
-(IBAction) keyPath;
-(IBAction) rac:(id) object;

@end

@interface Object: NSObject
-(IBAction) rac:(id) object;

@end

@interface Server: NSObject
-(IBAction) initialize;
-(IBAction) registerUser:(id) user;
-(IBAction) removePaymentCard:(id) cardInfo;
-(IBAction) setSitterCount:(id) count;
-(IBAction) subscribeToMessagesForAccount:(id) account;
-(IBAction) unsubscribeFromAccountMessages;
-(IBAction) processMessage:(id) message;
-(IBAction) shouldEmulateServer;

@end

@interface EmulatedServer: NSObject
-(IBAction) initialize;
-(IBAction) messagesFB;
-(IBAction) simulateSitterConfirmationDelay;

@end

@interface Storage: NSObject
-(IBAction) database;
-(IBAction) firebaseEnvironment;

@end

@interface UIFont: NSObject
-(IBAction) fontWithSymbolicTraits:(id) traits;

@end

@interface UIView: UIResponder
@end

@interface Scheduler: NSObject
-(IBAction) fire;
-(IBAction) fireAndDelay;
-(IBAction) initialize;
-(IBAction) applyTo:(id) views;
-(IBAction) originForIndex:(id) n;

@end

@interface Debounced: NSObject
-(IBAction) fireAndDelay;
-(IBAction) initialize;
-(IBAction) applyTo:(id) views;
-(IBAction) originForIndex:(id) n;

@end

@interface HexagonLayout: NSObject
-(IBAction) initialize;
-(IBAction) applyTo:(id) views;
-(IBAction) originForIndex:(id) n;

@end

